// frontend-vue/src/components/TripDialog.vue
<template>
  <v-dialog v-model="internalDialog">
    <v-card>
      <v-card-title>
        {{ props.trip?.id ? $t("tripDialog.titleEdit") : $t("tripDialog.titleCreate") }}
      </v-card-title>

      <form @submit.prevent="submit">
        <v-card-text>
          <v-text-field
            v-model="origin"
            :label="$t('tripDialog.origin')"
            :error-messages="originError"
          />
          <v-text-field
            v-model="destination"
            :label="$t('tripDialog.destination')"
            :error-messages="destinationError"
          />
          <v-date-input
            v-model="departure"
            input-format="dd-mm-yyyy"
            :label="$t('tripDialog.departureDate')"
            :error-messages="departureError"
            prepend-icon=""
          />
          <v-date-input
            v-model="returnDate"
            input-format="dd-mm-yyyy"
            :label="$t('tripDialog.returnDate')"
            :error-messages="returnDateError"
            prepend-icon=""
          />
          <v-text-field
            v-model="price"
            :label="$t('tripDialog.price')"
            type="number"
            :error-messages="priceError"
          />
          <v-checkbox v-model="isWorkTrip" :label="$t('tripDialog.workTrip')" />
        </v-card-text>

        <v-card-actions class="justify-end">
          <v-btn @click="$emit('close')">{{ $t("tripDialog.cancel") }}</v-btn>
          <v-btn type="submit" color="primary">{{ $t("tripDialog.save") }}</v-btn>
        </v-card-actions>
      </form>
    </v-card>
  </v-dialog>
</template>

<script setup>
import { ref, watch } from "vue";
import { useField, useForm } from "vee-validate";
import { useI18n } from "vue-i18n";

const props = defineProps(["modelValue", "trip"]);
const emit = defineEmits(["close", "save"]);

const { t } = useI18n();

const internalDialog = ref(false);

const { handleSubmit, resetForm } = useForm();

const { value: origin, errorMessage: originError } = useField("origin", (v) =>
  v ? true : t("validation.required")
);
const { value: destination, errorMessage: destinationError } = useField("destination", (v) =>
  v ? true : t("validation.required")
);
const { value: departure, errorMessage: departureError } = useField("departure", (v) =>
  v ? true : t("validation.required")
);
const { value: returnDate, errorMessage: returnDateError } = useField("returnDate", (v) =>
  v ? true : t("validation.required")
);
const { value: price, errorMessage: priceError } = useField("price", (v) => {
  if (v === "" || v === null || v === undefined) return t("validation.required");
  if (Number(v) < 0) return t("validation.minPrice");
  return true;
});
const { value: isWorkTrip } = useField("isWorkTrip");

watch(
  () => props.modelValue,
  (v) => {
    internalDialog.value = v;
    if (v) {
      resetForm({
        values: props.trip
          ? { ...props.trip }
          : {
              origin: "",
              destination: "",
              departure: "",
              returnDate: "",
              price: undefined,
              isWorkTrip: false
            }
      });
    }
  }
);

watch(
  () => props.trip,
  (trip) => {
    resetForm({
      values: trip
        ? { ...trip }
        : {
            origin: "",
            destination: "",
            departure: "",
            returnDate: "",
            price: undefined,
            isWorkTrip: false
          }
    });
  }
);

const submit = handleSubmit((values) => {
  emit("save", values);
});
</script>

// frontend-react-ts/src/features/trips/components/TripDialog.tsx
import { useEffect } from "react";
import { useForm, Controller } from "react-hook-form";
import { useTranslation } from "react-i18next";
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  Checkbox,
  FormControlLabel,
  Button,
  Stack
} from "@mui/material";
import { DatePicker } from "@mui/x-date-pickers";
import dayjs, { Dayjs } from "dayjs";
import { Trip, TripPayload } from "../../../types";

type TripDialogValues = {
  id?: number;
  origin: string;
  destination: string;
  departure: Dayjs | null;
  returnDate: Dayjs | null;
  price: number;
  isWorkTrip: boolean;
};

interface TripDialogProps {
  open: boolean;
  trip: Trip | null;
  onClose: () => void;
  onSave: (data: TripPayload) => void;
}

const emptyValues: TripDialogValues = {
  origin: "",
  destination: "",
  departure: null,
  returnDate: null,
  price: 0,
  isWorkTrip: false
};

export default function TripDialog({ open, trip, onClose, onSave }: TripDialogProps) {
  const { t } = useTranslation();
  const { control, handleSubmit, reset } = useForm<TripDialogValues>({ defaultValues: emptyValues });

  useEffect(() => {
    reset(
      trip
        ? {
            id: trip.id,
            origin: trip.origin,
            destination: trip.destination,
            departure: trip.departure ? dayjs(trip.departure) : null,
            returnDate: trip.returnDate ? dayjs(trip.returnDate) : null,
            price: trip.price,
            isWorkTrip: trip.isWorkTrip
          }
        : emptyValues
    );
  }, [trip, open, reset]);

  const onSubmit = (data: TripDialogValues) => {
    onSave({
      ...data,
      departure: data.departure ? data.departure.toDate() : null,
      returnDate: data.returnDate ? data.returnDate.toDate() : null
    });
  };

  return (
    <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm">
      <DialogTitle>{trip?.id ? t("tripDialog.titleEdit") : t("tripDialog.titleCreate")}</DialogTitle>
      <form onSubmit={handleSubmit(onSubmit)}>
        <DialogContent>
          <Stack spacing={2} sx={{ mt: 1 }}>
            <Controller
              name="origin"
              control={control}
              rules={{ required: t("validation.required") }}
              render={({ field, fieldState }) => (
                <TextField
                  {...field}
                  label={t("tripDialog.origin")}
                  fullWidth
                  error={!!fieldState.error}
                  helperText={fieldState.error?.message}
                />
              )}
            />
            <Controller
              name="destination"
              control={control}
              rules={{ required: t("validation.required") }}
              render={({ field, fieldState }) => (
                <TextField
                  {...field}
                  label={t("tripDialog.destination")}
                  fullWidth
                  error={!!fieldState.error}
                  helperText={fieldState.error?.message}
                />
              )}
            />
            <Controller
              name="departure"
              control={control}
              rules={{ required: t("validation.required") }}
              render={({ field, fieldState }) => (
                <DatePicker
                  label={t("tripDialog.departureDate")}
                  value={field.value}
                  onChange={field.onChange}
                  slotProps={{
                    textField: {
                      fullWidth: true,
                      error: !!fieldState.error,
                      helperText: fieldState.error?.message
                    }
                  }}
                />
              )}
            />
            <Controller
              name="returnDate"
              control={control}
              rules={{ required: t("validation.required") }}
              render={({ field, fieldState }) => (
                <DatePicker
                  label={t("tripDialog.returnDate")}
                  value={field.value}
                  onChange={field.onChange}
                  slotProps={{
                    textField: {
                      fullWidth: true,
                      error: !!fieldState.error,
                      helperText: fieldState.error?.message
                    }
                  }}
                />
              )}
            />
            <Controller
              name="price"
              control={control}
              rules={{
                required: t("validation.required"),
                min: { value: 0, message: t("validation.minPrice") }
              }}
              render={({ field, fieldState }) => (
                <TextField
                  {...field}
                  label={t("tripDialog.price")}
                  type="number"
                  fullWidth
                  value={field.value}
                  onChange={(e) => field.onChange(Number(e.target.value))}
                  error={!!fieldState.error}
                  helperText={fieldState.error?.message}
                />
              )}
            />
            <Controller
              name="isWorkTrip"
              control={control}
              render={({ field }) => (
                <FormControlLabel
                  control={
                    <Checkbox checked={field.value} onChange={(e) => field.onChange(e.target.checked)} />
                  }
                  label={t("tripDialog.workTrip")}
                />
              )}
            />
          </Stack>
        </DialogContent>
        <DialogActions>
          <Button onClick={onClose}>{t("tripDialog.cancel")}</Button>
          <Button type="submit" variant="contained" color="primary">
            {t("tripDialog.save")}
          </Button>
        </DialogActions>
      </form>
    </Dialog>
  );
}
