// frontend-react-ts/src/app/components/LocaleSwitcher.tsx
import { useTranslation } from "react-i18next";
import { Box, Button } from "@mui/material";

const LOCALES = [
  { code: "en", label: "EN" },
  { code: "es", label: "ES" }
];

export default function LocaleSwitcher() {
  const { i18n } = useTranslation();

  return (
    <Box display="flex" gap={0.5}>
      {LOCALES.map(({ code, label }, index) => (
        <Box key={code} display="flex" alignItems="center">
          <Button
            size="small"
            onClick={() => i18n.changeLanguage(code)}
            sx={{
              minWidth: "auto",
              fontWeight: i18n.language === code ? "bold" : "normal",
              color: i18n.language === code ? "primary.main" : "text.secondary",
              textDecoration: i18n.language === code ? "underline" : "none"
            }}
          >
            {label}
          </Button>
          {index < LOCALES.length - 1 && (
            <Box component="span" sx={{ color: "text.disabled", userSelect: "none" }}>
              |
            </Box>
          )}
        </Box>
      ))}
    </Box>
  );
}

// frontend-vue/src/app/components/LocaleSwitcher.vue
<template>
  <div class="d-flex align-center ga-1">
    <template v-for="(loc, index) in locales" :key="loc.code">
      <v-btn
        size="small"
        variant="text"
        :color="locale === loc.code ? 'primary' : undefined"
        :style="{
          fontWeight: locale === loc.code ? 'bold' : 'normal',
          textDecoration: locale === loc.code ? 'underline' : 'none',
        }"
        @click="locale = loc.code"
      >
        {{ loc.label }}
      </v-btn>
      <span v-if="index < locales.length - 1" class="text-disabled">|</span>
    </template>
  </div>
</template>

<script setup>
import { useI18n } from "vue-i18n";

const { locale } = useI18n();

const locales = [
  { code: "en", label: "EN" },
  { code: "es", label: "ES" },
];
</script>
