// frontend-vue/src/App.vue
<template>
  <v-app>
    <v-main>
      <div style="position: fixed; top: 16px; right: 16px; z-index: 1300;">
        <LocaleSwitcher />
      </div>
      <router-view />
    </v-main>
  </v-app>
</template>

<script setup>
import LocaleSwitcher from "./components/LocaleSwitcher.vue";
</script>

<style lang="scss">
html, body, #app {
  height: 100%;
  margin: 0;
}
</style>

// frontend-react/src/App.jsx
import { Routes, Route } from "react-router-dom";
import { CssBaseline, Box } from "@mui/material";
import LoginView from "./views/LoginView";
import DashboardView from "./views/DashboardView";
import LocaleSwitcher from "./components/LocaleSwitcher";

export default function App() {
  return (
    <>
      <CssBaseline />
      <Box sx={{ position: "fixed", top: 16, right: 16, zIndex: 1300 }}>
        <LocaleSwitcher />
      </Box>
      <Routes>
        <Route path="/" element={<LoginView />} />
        <Route path="/dashboard" element={<DashboardView />} />
      </Routes>
    </>
  );
}
