// frontend-react-ts/src/views/DashboardView/DashboardView.tsx
import { useState, useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { useNavigate } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { Container, Box, Button, Snackbar, Alert } from "@mui/material";
import { DataGrid, esES, enUS } from "@mui/x-data-grid";
import { dashboardColumns } from "./DashboardView.utils";
import TripDialog from "../../components/TripDialog";
import { getTrips, postTrip, putTrip, deleteTrip } from "../../api/trips";
import { setTrips, removeTrip } from "../../store/tripsSlice";
import { logout } from "../../store/authSlice";
import { AppDispatch, RootState } from "../../store";
import { Trip, TripPayload, SnackbarMessage } from "../../types";

export default function DashboardView() {
  const { t, i18n } = useTranslation();
  const dataGridLocale = i18n.language === "es"
    ? esES.components.MuiDataGrid.defaultProps.localeText
    : enUS.components.MuiDataGrid.defaultProps.localeText;

  const dispatch = useDispatch<AppDispatch>();
  const navigate = useNavigate();
  const trips = useSelector((state: RootState) => state.trips.trips);
  const [dialog, setDialog] = useState(false);
  const [selectedTrip, setSelectedTrip] = useState<Trip | null>(null);
  const [snackbar, setSnackbar] = useState<SnackbarMessage | null>(null);

  const loadTrips = async () => {
    const res = await getTrips();
    dispatch(setTrips(res.data));
  };

  useEffect(() => {
    loadTrips();
  }, []);

  const openDialog = () => {
    setSelectedTrip(null);
    setDialog(true);
  };

  const edit = (trip: Trip) => {
    setSelectedTrip(trip);
    setDialog(true);
  };

  const saveTrip = async (data: TripPayload) => {
    try {
      if (data.id) {
        await putTrip(data.id, data);
        setSnackbar({ severity: "success", text: t("dashboard.tripUpdated") });
      } else {
        await postTrip(data);
        setSnackbar({ severity: "success", text: t("dashboard.tripCreated") });
      }
      await loadTrips();
    } catch {
      setSnackbar({ severity: "error", text: data.id ? t("dashboard.errorUpdating") : t("dashboard.errorCreating") });
    } finally {
      setDialog(false);
    }
  };

  const remove = async (id?: number) => {
    if (id === undefined) return;
    try {
      await deleteTrip(id);
      dispatch(removeTrip(id));
      setSnackbar({ severity: "success", text: t("dashboard.tripDeleted") });
    } catch {
      setSnackbar({ severity: "error", text: t("dashboard.errorDeleting") });
    }
  };

  const handleLogout = () => {
    dispatch(logout());
    navigate("/");
  };

  return (
    <Container>
      <Box display="flex" justifyContent="flex-end" gap={2} my={2}>
        <Button variant="contained" color="primary" onClick={openDialog}>{t("dashboard.create")}</Button>
        <Button onClick={handleLogout}>{t("dashboard.logout")}</Button>
      </Box>
      <DataGrid
        rows={trips}
        columns={dashboardColumns(edit, remove, t)}
        autoHeight
        disableRowSelectionOnClick
        localeText={dataGridLocale}
      />
      <TripDialog
        open={dialog}
        trip={selectedTrip}
        onClose={() => setDialog(false)}
        onSave={saveTrip}
      />
      <Snackbar
        open={!!snackbar}
        autoHideDuration={3000}
        onClose={() => setSnackbar(null)}
        anchorOrigin={{ vertical: "bottom", horizontal: "center" }}
      >
        <Alert severity={snackbar?.severity} onClose={() => setSnackbar(null)}>
          {snackbar?.text}
        </Alert>
      </Snackbar>
    </Container>
  );
}

// frontend-vue/src/views/DashboardView.vue
<template>
  <v-container max-width="1200">
    <div class="d-flex justify-end">
      <v-btn class="mr-4" color="primary" @click="openDialog()">{{ $t("dashboard.create") }}</v-btn>
      <v-btn @click="logout">{{ $t("dashboard.logout") }}</v-btn>
    </div>
    <v-data-table :items="trips" :headers="headers">
      <template #item.departure="{ item }">
        {{ new Date(item.departure).toLocaleDateString() }}
      </template>
      <template #item.returnDate="{ item }">
        {{ new Date(item.returnDate).toLocaleDateString() }}
      </template>
      <template #item.isWorkTrip="{ item }">
        {{ item.isWorkTrip ? t("dashboard.columns.yes") : t("dashboard.columns.no") }}
      </template>
      <template #item.actions="{ item }">
        <v-btn variant="text" class="mr-3" icon @click="edit(item)">✏️</v-btn>
        <v-btn variant="text" icon @click="remove(item.id)">🗑️</v-btn>
      </template>
    </v-data-table>
    <TripDialog
      :modelValue="dialog"
      :trip="selectedTrip"
      @close="dialog = false"
      @save="saveTrip"
    />
    <v-snackbar-queue v-model="messages" closable />
  </v-container>
</template>

<script setup>
import { ref, onMounted, computed } from "vue";
import { useI18n } from "vue-i18n";
import { useTripStore } from "../stores/trips";
import { useAuthStore } from "../stores/auth";
import TripDialog from "../components/TripDialog.vue";
import { useRouter } from "vue-router"; 

const { t } = useI18n();

const tripStore = useTripStore();
const auth = useAuthStore();
const router = useRouter();

const dialog = ref(false);
const selectedTrip = ref(null);
const messages = ref([]);

const trips = computed(() => tripStore.trips);
const headers = computed(() => [
  { title: t("dashboard.columns.origin"), key: "origin" },
  { title: t("dashboard.columns.destination"), key: "destination" },
  { title: t("dashboard.columns.departure"), key: "departure" },
  { title: t("dashboard.columns.return"), key: "returnDate" },
  { title: t("dashboard.columns.price"), key: "price" },
  { title: t("dashboard.columns.workTrip"), key: "isWorkTrip" },
  { title: t("dashboard.columns.actions"), key: "actions" },
]);

onMounted(() => {
  tripStore.fetchTrips();
});

const openDialog = () => {
  selectedTrip.value = null;
  dialog.value = true;
};

const edit = (trip) => {
  selectedTrip.value = trip;
  dialog.value = true;
};

const saveTrip = async (data) => {
  try {
    if (data.id) {
      await tripStore.updateTrip(data.id, data);
      messages.value.push({
        color: "success",
        text: t("dashboard.tripUpdated"),
        timeout: 3000,
      });
    } else {
      await tripStore.createTrip(data);
      messages.value.push({
        color: "success",
        text: t("dashboard.tripCreated"),
        timeout: 3000,
      });
    }
  } catch (err) {
    messages.value.push({
      color: "error",
      text: data.id ? t("dashboard.errorUpdating") : t("dashboard.errorCreating"),
      timeout: 3000,
    });
  } finally {
    dialog.value = false;
  }
};

const remove = async (id) => {
  try {
    await tripStore.deleteTrip(id);
    messages.value.push({
      color: "success",
      text: t("dashboard.tripDeleted"),
      timeout: 3000,
    });
  } catch (err) {
    messages.value.push({
      color: "error",
      text: t("dashboard.errorDeleting"),
      timeout: 3000,
    });
  }
};

const logout = () => {
  auth.logout();
  router.push("/");
};
</script>
