// frontend-react/src/views/LoginView/LoginView.jsx
import { useState } from "react";
import { useDispatch } from "react-redux";
import { useNavigate } from "react-router-dom";
import { useTranslation } from "react-i18next";
import {
  Container,
  Card,
  CardContent,
  TextField,
  Button,
  Box,
  Typography,
  Snackbar,
  Alert
} from "@mui/material";
import { loginRequest, registerRequest } from "../../api/auth";
import { setAuth } from "../../store/authSlice";

export default function LoginView() {
  const { t } = useTranslation();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [isRegister, setIsRegister] = useState(false);
  const [snackbar, setSnackbar] = useState(null);

  const dispatch = useDispatch();
  const navigate = useNavigate();

  const handleSubmit = async () => {
    try {
      if (isRegister) {
        await registerRequest(email, password);
      }
      const res = await loginRequest(email, password);
      dispatch(setAuth(res.data));
      navigate("/dashboard");
    } catch {
      setSnackbar({ severity: "error", text: t("login.errorAuth") });
    }
  };

  return (
    <Container sx={{ height: "100%", display: "flex", alignItems: "center", justifyContent: "center" }}>
      <Card sx={{ width: 400 }}>
        <CardContent>
          <Typography variant="h6" mb={2}>
            {isRegister ? t("login.titleRegister") : t("login.title")}
          </Typography>
          <TextField
            label={t("login.email")}
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            fullWidth
            margin="normal"
          />
          <TextField
            label={t("login.password")}
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            fullWidth
            margin="normal"
          />
          <Box display="flex" justifyContent="space-between" mt={2}>
            <Button onClick={() => setIsRegister((v) => !v)}>
              {isRegister ? t("login.switchToLogin") : t("login.switchToRegister")}
            </Button>
            <Button variant="contained" color="primary" onClick={handleSubmit}>
              {isRegister ? t("login.register") : t("login.submit")}
            </Button>
          </Box>
        </CardContent>
      </Card>
      <Snackbar
        open={!!snackbar}
        autoHideDuration={3000}
        onClose={() => setSnackbar(null)}
        anchorOrigin={{ vertical: "bottom", horizontal: "center" }}
      >
        <Alert severity={snackbar?.severity} onClose={() => setSnackbar(null)}>
          {snackbar?.text}
        </Alert>
      </Snackbar>
    </Container>
  );
}

// frontend-vue/src/views/LoginView.vue
<template>
  <v-container class="d-flex align-center justify-center" style="height:100%">
    <v-card width="400">
      <v-card-title>
        {{ isRegister ? $t("login.titleRegister") : $t("login.title") }}
      </v-card-title>

      <v-card-text>
        <v-text-field v-model="email" :label="$t('login.email')" />
        <v-text-field v-model="password" :label="$t('login.password')" type="password" />
      </v-card-text>

      <v-card-actions class="d-flex justify-space-between">
        <v-btn variant="text" @click="toggleMode">
          {{ isRegister ? $t("login.switchToLogin") : $t("login.switchToRegister") }}
        </v-btn>

        <v-btn color="primary" @click="handleSubmit">
          {{ isRegister ? $t("login.register") : $t("login.submit") }}
        </v-btn>
      </v-card-actions>
    </v-card>
    <v-snackbar-queue v-model="messages" closable />
  </v-container>
</template>

<script setup>
import { ref } from "vue";
import { useI18n } from "vue-i18n";
import { useAuthStore } from "../stores/auth";
import { useRouter } from "vue-router";

const { t } = useI18n();

const email = ref("");
const password = ref("");
const isRegister = ref(false);
const messages = ref([]);

const auth = useAuthStore();
const router = useRouter();

const toggleMode = () => {
  isRegister.value = !isRegister.value;
};

const handleSubmit = async () => {
  try {
    if (isRegister.value) {
      await auth.register(email.value, password.value);
    } else {
      await auth.login(email.value, password.value);
    }

    router.push("/dashboard");
  } catch (err) {
    messages.value.push({
      color: "error",
      text: t("login.errorAuth"),
      timeout: 3000,
    });
  }
};
</script>
